import type {
  Activity,
  ApiFile,
  ApiVersion,
  Approval,
  Comment,
  Diff,
  Endpoint,
  Member,
  Notification,
  Project,
  Schema,
  User,
} from "./types";

export const initialCurrentUser: User = {
  id: "u1",
  name: "Sovannak",
  email: "sovannak@email.com",
  avatar: null,
  role: "owner",
  joinedAt: "2025-01-10",
  telegramEnabled: false,
  telegramHandle: "@sovannak_bot",
};

export const initialProjects: Project[] = [
  {
    id: "p1",
    name: "Payment API",
    description: "Core payment gateway APIs",
    memberCount: 3,
    apiCount: 2,
    versionCount: 3,
    createdAt: "2025-02-01",
  },
  {
    id: "p2",
    name: "User Service",
    description: "User management APIs",
    memberCount: 2,
    apiCount: 1,
    versionCount: 1,
    createdAt: "2025-03-15",
  },
];

export const initialMembers: Member[] = [
  {
    id: "u1",
    projectId: "p1",
    name: "Sovannak",
    email: "sovannak@email.com",
    role: "owner",
    avatar: null,
    joinedAt: "2025-01-10",
  },
  {
    id: "u2",
    projectId: "p1",
    name: "Dara",
    email: "dara@email.com",
    role: "contributor",
    avatar: null,
    joinedAt: "2025-02-20",
  },
  {
    id: "u3",
    projectId: "p1",
    name: "Mony",
    email: "mony@email.com",
    role: "reviewer",
    avatar: null,
    joinedAt: "2025-03-01",
  },
  {
    id: "u1b",
    projectId: "p2",
    name: "Sovannak",
    email: "sovannak@email.com",
    role: "owner",
    avatar: null,
    joinedAt: "2025-01-10",
  },
  {
    id: "u4",
    projectId: "p2",
    name: "Pisey",
    email: "pisey@email.com",
    role: "contributor",
    avatar: null,
    joinedAt: "2025-03-20",
  },
];

function makeFileUrl(projectId: string, fileName: string): string {
  return `https://storage.apilens.dev/projects/${projectId}/files/${fileName}`;
}

export const initialApiFiles: ApiFile[] = [
  {
    id: "f1",
    projectId: "p1",
    name: "payment-api-v1.yaml",
    format: "YAML",
    uploadedBy: "Dara",
    uploadedAt: "2025-02-10",
    fileUrl: makeFileUrl("p1", "payment-api-v1.yaml"),
  },
  {
    id: "f2",
    projectId: "p1",
    name: "payment-api-v2.json",
    format: "JSON",
    uploadedBy: "Sovannak",
    uploadedAt: "2025-03-05",
    fileUrl: makeFileUrl("p1", "payment-api-v2.json"),
  },
  {
    id: "f3",
    projectId: "p2",
    name: "user-service-v1.yaml",
    format: "YAML",
    uploadedBy: "Pisey",
    uploadedAt: "2025-03-20",
    fileUrl: makeFileUrl("p2", "user-service-v1.yaml"),
  },
];

export const initialVersions: ApiVersion[] = [
  {
    id: "v1",
    projectId: "p1",
    name: "v1",
    tags: ["stable"],
    status: "approved",
    createdBy: "Dara",
    createdAt: "2025-02-10",
    fileId: "f1",
  },
  {
    id: "v2",
    projectId: "p1",
    name: "v2",
    tags: ["beta-release"],
    status: "pending",
    createdBy: "Dara",
    createdAt: "2025-03-05",
    fileId: "f2",
  },
  {
    id: "v3",
    projectId: "p1",
    name: "v3",
    tags: ["draft"],
    status: "rejected",
    createdBy: "Sovannak",
    createdAt: "2025-04-01",
    fileId: "f2",
  },
  {
    id: "v4",
    projectId: "p2",
    name: "v1",
    tags: ["stable"],
    status: "approved",
    createdBy: "Pisey",
    createdAt: "2025-03-20",
    fileId: "f3",
  },
];

export const initialEndpoints: Endpoint[] = [
  {
    id: "e1",
    projectId: "p1",
    versionId: "v1",
    method: "GET",
    path: "/api/v1/payments",
    summary: "List all payments",
    description: "Returns a paginated list of payments for the current account.",
    parameters: [
      {
        name: "page",
        in: "query",
        required: false,
        type: "integer",
        description: "Page number",
        example: "1",
      },
      {
        name: "limit",
        in: "query",
        required: false,
        type: "integer",
        description: "Items per page (max 100)",
        example: "20",
      },
    ],
    responses: [
      {
        status: "200",
        description: "Array of payment objects",
        schemaName: "PaymentList",
        fields: [
          { name: "data", type: "Payment[]", required: true },
          { name: "total", type: "integer", required: true },
        ],
      },
      { status: "401", description: "Unauthorized" },
    ],
  },
  {
    id: "e2",
    projectId: "p1",
    versionId: "v1",
    method: "POST",
    path: "/api/v1/payments",
    summary: "Create a payment",
    description: "Creates a new payment transaction.",
    parameters: [],
    requestBody: [
      {
        name: "amount",
        type: "number",
        required: true,
        example: "9.99",
        description: "Amount in major currency units",
      },
      {
        name: "method",
        type: "string",
        required: true,
        example: "card",
      },
    ],
    responses: [
      {
        status: "201",
        description: "Created payment object",
        schemaName: "Payment",
      },
      { status: "400", description: "Validation error" },
    ],
  },
  {
    id: "e3",
    projectId: "p1",
    versionId: "v1",
    method: "GET",
    path: "/api/v1/payments/{id}",
    summary: "Get payment by ID",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        type: "string",
        description: "Payment ID",
        example: "pay_abc123",
      },
    ],
    responses: [
      { status: "200", description: "Payment object", schemaName: "Payment" },
      { status: "404", description: "Not found" },
    ],
  },
  {
    id: "e4",
    projectId: "p1",
    versionId: "v1",
    method: "DELETE",
    path: "/api/v1/payments/{id}",
    summary: "Delete a payment",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        type: "string",
        description: "Payment ID",
      },
    ],
    responses: [
      { status: "204", description: "No content" },
      { status: "404", description: "Not found" },
    ],
  },
  {
    id: "e5",
    projectId: "p1",
    versionId: "v2",
    method: "GET",
    path: "/api/v1/payments",
    summary: "List all payments",
    description:
      "Returns a paginated list of payments. Now includes metadata field.",
    parameters: [
      {
        name: "page",
        in: "query",
        required: false,
        type: "integer",
        description: "Page number",
        example: "1",
      },
      {
        name: "currency",
        in: "query",
        required: false,
        type: "string",
        description: "Filter by currency code (new in v2)",
        example: "USD",
      },
    ],
    responses: [
      {
        status: "200",
        description: "Array of payment objects with metadata",
        schemaName: "PaymentList",
        fields: [
          { name: "data", type: "Payment[]", required: true },
          { name: "total", type: "integer", required: true },
          { name: "metadata", type: "object", required: false },
        ],
      },
    ],
  },
  {
    id: "e6",
    projectId: "p1",
    versionId: "v2",
    method: "POST",
    path: "/api/v1/payments",
    summary: "Create a payment",
    description: "Creates a payment. Now requires currency code.",
    parameters: [],
    requestBody: [
      { name: "amount", type: "number", required: true, example: "9.99" },
      { name: "method", type: "string", required: true, example: "card" },
      {
        name: "currency",
        type: "string",
        required: true,
        example: "USD",
        description: "ISO 4217 currency code (NEW required field)",
      },
    ],
    responses: [
      { status: "201", description: "Created payment", schemaName: "Payment" },
      { status: "400", description: "Validation error" },
    ],
  },
  {
    id: "e7",
    projectId: "p1",
    versionId: "v2",
    method: "GET",
    path: "/api/v1/payments/{id}",
    summary: "Get payment by ID",
    description: "Returns the payment, now includes optional metadata.",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        type: "string",
        description: "Payment ID",
      },
    ],
    responses: [
      {
        status: "200",
        description: "Payment object with optional metadata",
        schemaName: "Payment",
        fields: [
          { name: "id", type: "string", required: true },
          { name: "amount", type: "number", required: true },
          { name: "currency", type: "string", required: true },
          { name: "metadata", type: "object", required: false },
        ],
      },
    ],
  },
  {
    id: "e8",
    projectId: "p1",
    versionId: "v2",
    method: "GET",
    path: "/api/v1/payments/export",
    summary: "Export payments as CSV",
    description: "New in v2. Streams a CSV report of all payments.",
    parameters: [
      {
        name: "from",
        in: "query",
        required: false,
        type: "string",
        description: "ISO date",
      },
      {
        name: "to",
        in: "query",
        required: false,
        type: "string",
        description: "ISO date",
      },
    ],
    responses: [{ status: "200", description: "CSV file stream" }],
  },
  {
    id: "e9",
    projectId: "p2",
    versionId: "v4",
    method: "GET",
    path: "/api/v1/users/{id}",
    summary: "Get user by ID",
    parameters: [
      { name: "id", in: "path", required: true, type: "string" },
    ],
    responses: [
      { status: "200", description: "User object" },
      { status: "404", description: "Not found" },
    ],
  },
];

export const initialSchemas: Schema[] = [
  {
    id: "s1",
    projectId: "p1",
    versionId: "v1",
    name: "Payment",
    fields: [
      { name: "id", type: "string", required: true, example: "pay_abc123" },
      { name: "amount", type: "number", required: true, example: "9.99" },
      { name: "method", type: "string", required: true, example: "card" },
      { name: "createdAt", type: "string (ISO date)", required: true },
    ],
  },
  {
    id: "s2",
    projectId: "p1",
    versionId: "v1",
    name: "PaymentList",
    fields: [
      { name: "data", type: "Payment[]", required: true },
      { name: "total", type: "integer", required: true },
    ],
  },
  {
    id: "s3",
    projectId: "p1",
    versionId: "v2",
    name: "Payment",
    fields: [
      { name: "id", type: "string", required: true },
      { name: "amount", type: "number", required: true },
      { name: "currency", type: "string", required: true },
      { name: "method", type: "string", required: true },
      { name: "metadata", type: "object", required: false },
      { name: "createdAt", type: "string (ISO date)", required: true },
    ],
  },
  {
    id: "s4",
    projectId: "p1",
    versionId: "v2",
    name: "PaymentList",
    fields: [
      { name: "data", type: "Payment[]", required: true },
      { name: "total", type: "integer", required: true },
      { name: "metadata", type: "object", required: false },
    ],
  },
];

export const initialDiffs: Diff[] = [
  {
    id: "d1",
    projectId: "p1",
    fromVersion: "v1",
    toVersion: "v2",
    endpoint: "POST /api/v1/payments",
    changeType: "breaking",
    subType: "optional_to_required",
    description: "Required field `currency` added to request body",
    oldValue: "currency: not present",
    newValue: "currency: string (required)",
    impactLevel: "high",
    plainExplanation:
      "The `currency` field is now required. Any existing integrations that don't send this field will break.",
  },
  {
    id: "d2",
    projectId: "p1",
    fromVersion: "v1",
    toVersion: "v2",
    endpoint: "GET /api/v1/payments/{id}",
    changeType: "non-breaking",
    subType: "optional_field_added",
    description: "New optional field `metadata` added to response",
    oldValue: "-",
    newValue: "metadata: object (optional)",
    impactLevel: "low",
    plainExplanation:
      "The response now includes an optional `metadata` field. Existing clients keep working unchanged.",
  },
  {
    id: "d3",
    projectId: "p1",
    fromVersion: "v1",
    toVersion: "v2",
    endpoint: "DELETE /api/v1/payments/{id}",
    changeType: "breaking",
    subType: "endpoint_removed",
    description: "Endpoint removed",
    oldValue: "DELETE /api/v1/payments/{id}: exists",
    newValue: "-",
    impactLevel: "high",
    plainExplanation:
      "The DELETE endpoint has been removed. Any client that currently deletes payments will break.",
  },
  {
    id: "d4",
    projectId: "p1",
    fromVersion: "v1",
    toVersion: "v2",
    endpoint: "GET /api/v1/payments/export",
    changeType: "non-breaking",
    subType: "endpoint_added",
    description: "New endpoint added",
    oldValue: "-",
    newValue: "GET /api/v1/payments/export",
    impactLevel: "low",
    plainExplanation:
      "A new export endpoint was added. Existing integrations are not affected.",
  },
  {
    id: "d5",
    projectId: "p1",
    fromVersion: "v1",
    toVersion: "v2",
    endpoint: "GET /api/v1/payments",
    changeType: "non-breaking",
    subType: "optional_param_added",
    description: "Optional query param `currency` added",
    oldValue: "-",
    newValue: "currency: string (optional)",
    impactLevel: "low",
    plainExplanation:
      "An optional `currency` filter was added. No effect on existing callers.",
  },
];

export const initialApprovals: Approval[] = [
  {
    id: "a1",
    projectId: "p1",
    fromVersion: "v1",
    toVersion: "v2",
    submittedBy: "Dara",
    submittedAt: "2025-03-05",
    status: "pending",
    reviewerComment: null,
  },
  {
    id: "a2",
    projectId: "p1",
    fromVersion: "v2",
    toVersion: "v3",
    submittedBy: "Dara",
    submittedAt: "2025-04-01",
    status: "rejected",
    reviewerComment: "Breaking changes need justification.",
  },
];

export const initialComments: Comment[] = [
  {
    id: "c1",
    approvalId: "a1",
    endpointId: "e6",
    endpoint: "POST /api/v1/payments",
    author: "Mony",
    text: "Why is currency now required?",
    createdAt: "2025-03-06",
  },
  {
    id: "c2",
    approvalId: "a1",
    endpointId: "e6",
    endpoint: "POST /api/v1/payments",
    author: "Dara",
    text: "Multi-currency support requirement.",
    createdAt: "2025-03-06",
  },
];

export const initialNotifications: Notification[] = [
  {
    id: "n1",
    projectId: "p1",
    type: "approval",
    message: "Dara submitted v2 for review",
    read: false,
    createdAt: "2025-03-05",
    href: "/projects/p1/workflow/a1",
  },
  {
    id: "n2",
    projectId: "p1",
    type: "comment",
    message: "Mony commented on POST /api/v1/payments",
    read: false,
    createdAt: "2025-03-06",
    href: "/projects/p1/workflow/a1",
  },
  {
    id: "n3",
    projectId: "p1",
    type: "rejection",
    message: "v3 was rejected by Mony",
    read: true,
    createdAt: "2025-04-01",
    href: "/projects/p1/workflow",
  },
];

export const initialActivities: Activity[] = [
  {
    id: "ac1",
    projectId: "p1",
    user: "Dara",
    action: "Uploaded",
    target: "payment-api-v2.json",
    timestamp: "2025-03-05T09:00:00Z",
  },
  {
    id: "ac2",
    projectId: "p1",
    user: "Dara",
    action: "Submitted",
    target: "v2 for review",
    timestamp: "2025-03-05T09:30:00Z",
  },
  {
    id: "ac3",
    projectId: "p1",
    user: "Mony",
    action: "Commented",
    target: "POST /api/v1/payments",
    timestamp: "2025-03-06T11:00:00Z",
  },
  {
    id: "ac4",
    projectId: "p1",
    user: "Mony",
    action: "Rejected",
    target: "v3",
    timestamp: "2025-04-01T14:00:00Z",
  },
  {
    id: "ac5",
    projectId: "p1",
    user: "Sovannak",
    action: "Invited",
    target: "Dara as Contributor",
    timestamp: "2025-02-20T10:00:00Z",
  },
];
